language: python
sudo: required
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
services:
- docker
python:
- 3.6
- 3.5
- 3.4
- 2.7
install:
- pip install tox tox-travis twine
- pip install --upgrade setuptools
- make api
script:
- tox --workdir api
after_success:
- make deploy_pypi
deploy:
  provider: releases
  api_key:
    secure: S8DScmD1i3Ripc7hPE9EdFpgIWbLdFfUo/I59utbQMiQKUDs4LhaLjUy1KLbEZm6ZDZtDQwo7rem1EReJdwSHHy9/bAXfdT3u3MgwzlrT76S4u7Xi+yhT5g2ixm5AM6jJ3xai3u4JJ0NFoQKFGJD7HTt5EyzjJSuDLSZ7PEzjI4z4N6nm0P17XCLAGvRwAjxRJhZCVvbVhFaQ9HgsZH4C1mPtxb44Kl8aRhrBJ9dQVxcGJn5WrrSroGvSa/spwV9STyQi3X1tPDa28qmFrx6q8gVM6wmWJNKA2FHC1SEyWiFE/78Iu/nBfQzoLjoDlmD5ndkVNAn2T19ZFv7i8SBkIZ414w4IhNIQ2UcxhLS3y4xNoEkOmWFQ03rLa0DzpyJ+8PU17lhsSxCfO4lQbi63jjzQnFG7sy1bj3gcLkpP1J6eUkuSnjFkGPcLiKt7cegltwP59Wm8gAlQq5o1fgtcI4VLMrS0jR+F+GNlL7M1eYD3FTgFquHpDAw7rY1RDDryu23nNVqm/DZaE5w0DF75bqmhAeLxnOpavpTLoItxgv+DIFsmaEkCdbxuypBjcgd5TDksNvsJzr3f/FbF3xSgEp0uEt10da8/a4iW1cUoJCiJUeTWJsYM3t3fs90oaBpvkcdTBr9JzIl2BLmIJugPSPEhJqEMCERa1SZQGaGpks=
  file_glob: true
  file:
    - dist/*
  on:
    repo: rienafairefr/pybridge
    tags: true
