.PHONY: clean

VERSION ?= $(shell pipenv run python -c "from setuptools_scm import get_version;print(get_version())")
OPENAPIGEN_VERSION ?= v4.2.3

clean:
	rm -rf api

docker_image: $(wildcard generator/**/*) $(wildcard generator/*)
	docker build -t pybridgeapi-custom-codegen generator

api: openapi.yaml Makefile docker_image $(wildcard templates/**/*) $(wildcard templates/*)
	docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local pybridgeapi-custom-codegen \
	           generate -i /local/openapi.yaml \
	           --git-user-id rienafairefr \
	           --git-repo-id pybridgeapi \
	           -t /local/templates \
	           -g eu.rienafairefr.customcodegen.PythonCustomCodegen -o /local/api \
	           -p packageName=bridge \
	           -p projectName=pybridgeapi \
	           -p packageVersion="$(VERSION)" \
	           -p appName="pybridgeapi" \
	           -p infoEmail="rienafairefr@gmail.com" \
	           -p appDescription="This is pybridgeapi, an autogenerated package to access bridgeapi.io"
