# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybridge
from pybridge.models.inline_response2004 import InlineResponse2004  # noqa: E501
from pybridge.rest import ApiException


class TestInlineResponse2004(unittest.TestCase):
    """InlineResponse2004 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004(self):
        """Test InlineResponse2004"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pybridge.models.inline_response2004.InlineResponse2004()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
