# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybridge
from pybridge.api.default_api import DefaultApi  # noqa: E501
from pybridge.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = pybridge.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate_user(self):
        """Test case for authenticate_user

        Authenticate a User  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
