# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybridge
from pybridge.models.parent_bank import ParentBank  # noqa: E501
from pybridge.rest import ApiException


class TestParentBank(unittest.TestCase):
    """ParentBank unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParentBank(self):
        """Test ParentBank"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pybridge.models.parent_bank.ParentBank()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
