# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybridge
from pybridge.models.empty_body import EmptyBody  # noqa: E501
from pybridge.rest import ApiException


class TestEmptyBody(unittest.TestCase):
    """EmptyBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmptyBody(self):
        """Test EmptyBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pybridge.models.empty_body.EmptyBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
