# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybridge
from pybridge.models.inline_response200_pagination import InlineResponse200Pagination  # noqa: E501
from pybridge.rest import ApiException


class TestInlineResponse200Pagination(unittest.TestCase):
    """InlineResponse200Pagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200Pagination(self):
        """Test InlineResponse200Pagination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pybridge.models.inline_response200_pagination.InlineResponse200Pagination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
