# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BankCountry(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'country_code': 'str',
        'parent_banks': 'list[ParentBank]'
    }

    attribute_map = {
        'country_code': 'country_code',
        'parent_banks': 'parent_banks'
    }

    def __init__(self, country_code=None, parent_banks=None):  # noqa: E501
        """BankCountry - a model defined in OpenAPI"""  # noqa: E501

        self._country_code = None
        self._parent_banks = None
        self.discriminator = None

        if country_code is not None:
            self.country_code = country_code
        if parent_banks is not None:
            self.parent_banks = parent_banks

    @property
    def country_code(self):
        """Gets the country_code of this BankCountry.  # noqa: E501


        :return: The country_code of this BankCountry.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this BankCountry.


        :param country_code: The country_code of this BankCountry.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    @property
    def parent_banks(self):
        """Gets the parent_banks of this BankCountry.  # noqa: E501


        :return: The parent_banks of this BankCountry.  # noqa: E501
        :rtype: list[ParentBank]
        """
        return self._parent_banks

    @parent_banks.setter
    def parent_banks(self, parent_banks):
        """Sets the parent_banks of this BankCountry.


        :param parent_banks: The parent_banks of this BankCountry.  # noqa: E501
        :type: list[ParentBank]
        """

        self._parent_banks = parent_banks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BankCountry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
