# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Bank(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'resource_uri': 'str',
        'resource_type': 'str',
        'name': 'str',
        'country_code': 'str',
        'automatic_refresh': 'bool',
        'form': 'list[BankForm]'
    }

    attribute_map = {
        'id': 'id',
        'resource_uri': 'resource_uri',
        'resource_type': 'resource_type',
        'name': 'name',
        'country_code': 'country_code',
        'automatic_refresh': 'automatic_refresh',
        'form': 'form'
    }

    def __init__(self, id=None, resource_uri=None, resource_type=None, name=None, country_code=None, automatic_refresh=None, form=None):  # noqa: E501
        """Bank - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._resource_uri = None
        self._resource_type = None
        self._name = None
        self._country_code = None
        self._automatic_refresh = None
        self._form = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if resource_uri is not None:
            self.resource_uri = resource_uri
        if resource_type is not None:
            self.resource_type = resource_type
        if name is not None:
            self.name = name
        if country_code is not None:
            self.country_code = country_code
        if automatic_refresh is not None:
            self.automatic_refresh = automatic_refresh
        if form is not None:
            self.form = form

    @property
    def id(self):
        """Gets the id of this Bank.  # noqa: E501


        :return: The id of this Bank.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Bank.


        :param id: The id of this Bank.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def resource_uri(self):
        """Gets the resource_uri of this Bank.  # noqa: E501


        :return: The resource_uri of this Bank.  # noqa: E501
        :rtype: str
        """
        return self._resource_uri

    @resource_uri.setter
    def resource_uri(self, resource_uri):
        """Sets the resource_uri of this Bank.


        :param resource_uri: The resource_uri of this Bank.  # noqa: E501
        :type: str
        """

        self._resource_uri = resource_uri

    @property
    def resource_type(self):
        """Gets the resource_type of this Bank.  # noqa: E501


        :return: The resource_type of this Bank.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this Bank.


        :param resource_type: The resource_type of this Bank.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def name(self):
        """Gets the name of this Bank.  # noqa: E501


        :return: The name of this Bank.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Bank.


        :param name: The name of this Bank.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def country_code(self):
        """Gets the country_code of this Bank.  # noqa: E501


        :return: The country_code of this Bank.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this Bank.


        :param country_code: The country_code of this Bank.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    @property
    def automatic_refresh(self):
        """Gets the automatic_refresh of this Bank.  # noqa: E501


        :return: The automatic_refresh of this Bank.  # noqa: E501
        :rtype: bool
        """
        return self._automatic_refresh

    @automatic_refresh.setter
    def automatic_refresh(self, automatic_refresh):
        """Sets the automatic_refresh of this Bank.


        :param automatic_refresh: The automatic_refresh of this Bank.  # noqa: E501
        :type: bool
        """

        self._automatic_refresh = automatic_refresh

    @property
    def form(self):
        """Gets the form of this Bank.  # noqa: E501


        :return: The form of this Bank.  # noqa: E501
        :rtype: list[BankForm]
        """
        return self._form

    @form.setter
    def form(self, form):
        """Sets the form of this Bank.


        :param form: The form of this Bank.  # noqa: E501
        :type: list[BankForm]
        """

        self._form = form

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Bank):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
