# coding: utf-8

"""
    Bridge API

    bridgeapi.io  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ParentBank(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'logo_url': 'str',
        'banks': 'list[Bank]'
    }

    attribute_map = {
        'name': 'name',
        'logo_url': 'logo_url',
        'banks': 'banks'
    }

    def __init__(self, name=None, logo_url=None, banks=None):  # noqa: E501
        """ParentBank - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._logo_url = None
        self._banks = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if logo_url is not None:
            self.logo_url = logo_url
        if banks is not None:
            self.banks = banks

    @property
    def name(self):
        """Gets the name of this ParentBank.  # noqa: E501


        :return: The name of this ParentBank.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ParentBank.


        :param name: The name of this ParentBank.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def logo_url(self):
        """Gets the logo_url of this ParentBank.  # noqa: E501


        :return: The logo_url of this ParentBank.  # noqa: E501
        :rtype: str
        """
        return self._logo_url

    @logo_url.setter
    def logo_url(self, logo_url):
        """Sets the logo_url of this ParentBank.


        :param logo_url: The logo_url of this ParentBank.  # noqa: E501
        :type: str
        """

        self._logo_url = logo_url

    @property
    def banks(self):
        """Gets the banks of this ParentBank.  # noqa: E501


        :return: The banks of this ParentBank.  # noqa: E501
        :rtype: list[Bank]
        """
        return self._banks

    @banks.setter
    def banks(self, banks):
        """Sets the banks of this ParentBank.


        :param banks: The banks of this ParentBank.  # noqa: E501
        :type: list[Bank]
        """

        self._banks = banks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ParentBank):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
